Task: MediaPipe_Pose
scorer: User
date: Jan27
multianimalproject: false
identity: null
project_path: /app/data/Parra-Data/Disk/Motion-Tracking/MediaPipe_Pose-User-2026-01-27
engine: pytorch
video_sets:
  ? /app/data/Parra-Data/Disk/Motion-Tracking/MediaPipe_Pose-User-2026-01-27/videos/calib_man_cam0_20251225_122006_1_trig1_fps30_exposure5000_gain23_overlay.mp4
  : crop: 0, 1024, 0, 1024
bodyparts:
- '0'
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
- '10'
- '11'
- '12'
- '13'
- '14'
- '15'
- '16'
- '17'
- '18'
- '19'
- '20'
- '21'
- '22'
- '23'
- '24'
- '25'
- '26'
- '27'
- '28'
- '29'
- '30'
- '31'
- '32'
start: 0
stop: 1
numframes2pick: 50
skeleton:
- - bodypart1
  - bodypart2
- - objectA
  - bodypart3
skeleton_color: black
pcutoff: 0.6
dotsize: 12
alphavalue: 0.7
colormap: rainbow
TrainingFraction:
- 0.95
iteration: 0
default_net_type: resnet_50
default_augmenter: default
snapshotindex: -1
detector_snapshotindex: -1
batch_size: 16
detector_batch_size: 1
cropping: false
x1: 0
x2: 640
y1: 277
y2: 624
corner2move2:
- 50
- 50
move2corner: true
SuperAnimalConversionTables: null
